map_manager:
  frame_id: "map"

ros_gui_node:
  pub_map_topic: "/map_manager/map"
  sub_map_topic: "/map"
  save_map_timeout: 2.0
  free_thresh_default: 0.25
  occupied_thresh_default: 0.65
  map_subscribe_transient_local: true

web_server:
  port: 7684
